/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
 * Generated on: 09-Mar-2016 14:29:11
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 26
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */

#define BL 26
float B[26] = {
   0.008084530644324,  0.02164117317308, -0.00320142266981, -0.01032774000832,
    0.02114684174663, -0.02217335966656, 0.006510702547366,  0.02467168641858,
   -0.05837370626346,  0.07145822914931, -0.03568578219724, -0.09059341273444,
     0.5915294505179,   0.5915294505179, -0.09059341273444, -0.03568578219724,
    0.07145822914931, -0.05837370626346,  0.02467168641858, 0.006510702547366,
   -0.02217335966656,  0.02114684174663, -0.01032774000832, -0.00320142266981,
    0.02164117317308, 0.008084530644324
};
