/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
 * Generated on: 09-Mar-2016 14:29:11
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 26
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */

#define BL 20
float B[20] = {
	0.01473689062126,  0.03120077332855, -0.01917812587353, 0.001465844681742,
	0.027181348792, -0.05680530037999,   0.0663618841327, -0.02906100731935,
	-0.09607979789343,   0.5936476098974,   0.5936476098974, -0.09607979789343,
	-0.02906100731935,   0.0663618841327, -0.05680530037999,    0.027181348792,
	0.001465844681742, -0.01917812587353,  0.03120077332855,  0.01473689062126
};
